services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    networks:
      - net-algo
    volumes:
      - storage-db-pgsql:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD_ROOT}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - net-algo
    volumes:
      - storage-db-mysql:/var/lib/mysql

networks:
  net-algo:

volumes:
  storage-db-pgsql:
  storage-db-mysql: